### ISSUE TITLE
Add title attribute to report Plot

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/pbcommand#147]
The lack of explicit title attribute is resulting the UI using "caption" as the display name. 

I believe this is for historical reasons, but I don't recall the specifics.

**Comment by evolvedmicrobe** [comment]
I think we should also add an explicit title attribute to the plotGroup and tables, right now these are just arrays and don't have any information about what the "Group of Plots" or "Group of Tables" should be called.

**Comment by mpkocher** [comment]
A PlotGroup has a title

https://github.com/PacificBiosciences/pbcommand/blob/master/pbcommand/models/report.py#L226

There is not TableGroup data model, but a Table also has a title:

https://github.com/PacificBiosciences/pbcommand/blob/master/pbcommand/models/report.py#L362

**Comment by mpkocher** [comment]
Added in pbcommand 0.4.3. 

Fixed with a340a4350a07d203aedaae6f33de4e498c45ffc2

**Comment by evolvedmicrobe** [comment]
I was thinking more of `plotGroups` and `Tables` rather than the singular version.  Right now these are just arrays, but it occurs to me we might want some higher level grouping of tables/plots. 

For example, there will be times when we will want the same information appearing in the same tab - e.g. An accuracy violin plot with a table showing the numbers underneath.  Do we have a way to structure the output at the report level to combine multiple items into one page? I gather the fundamental unit seems to be the report.json file, and am not sure if it's possible to put in any sub-groupings for display
